name = "Wflow"
uuid = "d48b7d99-76e7-47ae-b1d5-ff0c1cf9a818"
version = "1.0.0-dev"
authors = ["Deltares and contributors"]

[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
BasicModelInterface = "59605e27-edc0-445a-b93d-c09a3a50b330"
CFTime = "179af706-886a-5703-950a-314cd64e0468"
CompositionsBase = "a33af91c-f02d-484b-be07-31d278c5ca2b"
ConstructionBase = "187b0558-2788-49d3-abe0-74a17ed4e7c9"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
EnumX = "4e289a0a-7415-4d19-859d-a7e5c4648b56"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
LoggingExtras = "e6f89c97-d47a-5376-807f-9c37f3926c36"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Polyester = "f517fe37-dbe3-4b94-8317-1923a5111588"
ProgressLogging = "33c8b6b6-d38a-422a-b730-caa89a2f386c"
PropertyDicts = "f8a19df8-e894-5f55-a973-672c1158cbca"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
TerminalLoggers = "5d786b92-1e48-4d6f-9151-6b4477ca9bed"

[compat]
Accessors = "0.1"
Aqua = "0.8"
BasicModelInterface = "0.1"
CFTime = "0.1, 0.2"
CompositionsBase = "0.1.2"
ConstructionBase = "1.6.0"
Dates = "1"
DelimitedFiles = "1"
Downloads = "1"
EnumX = "1.0.5"
FillArrays = "1.14.0"
Glob = "1.3"
Graphs = "1.4"
LoggingExtras = "0.4.6,0.5,1"
NCDatasets = "0.13.2, 0.14"
Parameters = "0.12"
Polyester = "0.7.10"
Polynomials = "3,4"
ProgressLogging = "0.1"
PropertyDicts = "0.2.1"
QuadGK = "2"
Random = "1"
SpecialFunctions = "2.5.1"
StaticArrays = "0.12,1.0"
Statistics = "1"
TOML = "1"
TerminalLoggers = "0.1.5"
Test = "1"
TestItemRunner = "1.1"
julia = "1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"

[targets]
test = ["Aqua", "Downloads", "Polynomials", "QuadGK", "SpecialFunctions", "Test", "TestItemRunner", "Random"]
