name = "Wflow"
uuid = "d48b7d99-76e7-47ae-b1d5-ff0c1cf9a818"
authors = ["Deltares and contributors"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CFTime = "179af706-886a-5703-950a-314cd64e0468"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"

[compat]
BenchmarkTools = "0.5"
CFTime = "0.1"
CSV = "0.6, 0.7"
LightGraphs = "1.3"
NCDatasets = "0.10.4"
StaticArrays = "0.12"
UnPack = "1"
julia = "1.5"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Random", "Test"]
