name = "Wflow"
uuid = "d48b7d99-76e7-47ae-b1d5-ff0c1cf9a818"
authors = ["Deltares and contributors"]
version = "0.1.0"

[deps]
BasicModelInterface = "59605e27-edc0-445a-b93d-c09a3a50b330"
CFTime = "179af706-886a-5703-950a-314cd64e0468"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
FieldMetadata = "bf96fef3-21d2-5d20-8afa-0e7d4c32a885"
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
ProgressLogging = "33c8b6b6-d38a-422a-b730-caa89a2f386c"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"

[compat]
BasicModelInterface = "0.1"
CFTime = "0.1"
FieldMetadata = "0.3"
LightGraphs = "1.3"
NCDatasets = "0.10.4, 0.11"
Parameters = "0.12"
StaticArrays = "0.12, 1.0"
TOML = "1.0"
UnPack = "1"
julia = "1.5"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["BenchmarkTools", "Logging", "Polynomials", "Random", "Test"]
