name = "WflowServer"
uuid = "6f3aa2dc-f527-41f4-85fc-b3cbabe74cf6"
authors = ["Deltares and contributors"]
manifest = "../Manifest.toml"
version = "0.1.0"

[deps]
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
StructTypes = "856f2bd8-1eba-4b0a-8007-ebc267875bd4"
Wflow = "d48b7d99-76e7-47ae-b1d5-ff0c1cf9a818"
ZMQ = "c2297ded-f4af-51ae-bb23-16f91089e4e1"

[compat]
JSON3 = "1.14"
StructTypes = "1.10"
ZMQ = "1.2"
julia = "1.10"

[extras]
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Downloads", "Statistics", "Test"]
