name = "WflowServer"
uuid = "6f3aa2dc-f527-41f4-85fc-b3cbabe74cf6"
authors = ["Deltares and contributors"]
version = "0.1.0"

[workspace]
projects = ["test"]

[deps]
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
StructTypes = "856f2bd8-1eba-4b0a-8007-ebc267875bd4"
Wflow = "d48b7d99-76e7-47ae-b1d5-ff0c1cf9a818"
ZMQ = "c2297ded-f4af-51ae-bb23-16f91089e4e1"

[compat]
JSON3 = "1.14"
Logging = "1"
StructTypes = "1.10"
Wflow = "1"
ZMQ = "1.2"
julia = "1.10"
