name: Update SBOM
on:
  push:
      branches:
        - 'master'
      paths:
        - 'Wflow/Manifest.toml'
  # on demand
  workflow_dispatch:
jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - uses: prefix-dev/setup-pixi@v0.9.3
        with:
          pixi-version: "latest"
      - name: Install Julia and update SBOM file
        run: |
          pixi run install-julia
          pixi run generate-sbom
        env:
          JULIA_PKG_PRECOMPILE_AUTO: "0"
      - uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.CI_PR_PAT }}
          branch: update/sbom
          title: Update SBOM
          commit-message: "Update SBOM"
          author: "GitHub <noreply@github.com>"
